# Generated by Django 5.2.8 on 2025-11-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_alter_exam_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Date and time of the exam')),
                ('description', models.TextField(blank=True)),
                ('grade', models.IntegerField(choices=[(1, 'الصف الأول'), (2, 'الصف الثاني'), (3, 'الصف الثالث'), (4, 'الصف الرابع')])),
                ('type', models.IntegerField(choices=[(1, 'شهري'), (2, 'فاينل'), (3, 'يومي')])),
                ('study_type', models.IntegerField(choices=[(1, 'صباحي'), (2, 'مسائي')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='exams.subject')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
