# Generated by Django 5.2.8 on 2025-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_schedule', '0002_alter_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
