# Generated by Django 5.2.8 on 2025-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='study_type',
            field=models.IntegerField(choices=[(1, 'صباحي'), (2, 'مسائي')], default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.IntegerField(choices=[(1, 'الصف الأول'), (2, 'الصف الثاني'), (3, 'الصف الثالث'), (4, 'الصف الرابع')]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.IntegerField(choices=[(1, 'شهري'), (2, 'فاينل'), (3, 'يومي')]),
        ),
    ]
